version: '3'
services:
  db:
    container_name: postgres
    hostname: db
    image: postgres:13.1
    restart: on-failure
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
    ports:
      - 5432:5432
