spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/users
    driver-class-name: org.postgresql.Driver
    username: root
    password: postgres
    hikari:
      username: root
      password: postgres

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernates:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
